version : '3'
services:
   sylanos-app:
    build:
      context: .
      dockerfile: Dockerfile 
    restart: always
    ports:
      - '5001:5001'
    environment: 
     - PORT=5001
     - DB_URI=mongodb://admin:password@mongodb/silianos?authSource=admin
     - CLOUDINARY_CLOUD_NAME=dml9ph1zz
     - CLOUDINARY_API_KEY=853763549933934
     - CLOUDINARY_API_SECRET=M4ZIUhSRUsJLzuDGqyqp862Mf6c
     - JWT_ACCOUNT_ACTIVATION=hdshyeutoasxlmgmbndpo5665820179djskhzaid
     - JWT_SECRET=Jmd=^?Q!jFh5H#py
     - JWT_RESET_PASSWORD=L({GZ4#sMhV4}+{6  
     - EMAIL=xxxxx
     - EMAIL_FROM=xxxx
     - PASSWORD=xxxx
    depends_on:
      -  mongodb
    networks:
      -  node-network-sylanos
   mongodb: 
      image: mongo
      container_name:  mongo
      restart: always
      ports:
       - 27017:27017
      environment:
       - MONGO_INITDB_ROOT_USERNAME=admin
       - MONGO_INITDB_ROOT_PASSWORD=password
      volumes:
       -  data-sylanos:/data/db
      networks:
      -  node-network-sylanos
   mongo-express-sylanos:
     image : mongo-express
     container_name:  mongo-express-sylanos
     restart: always
     ports:
      - 8081:8081
     environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
     networks:
      -  node-network-sylanos
volumes:
  data-sylanos:
    driver: local
networks:
  node-network-sylanos:
    driver: bridge
